package main

import (
	"strings"
	"testing"
)

func TestCanonicalizeGeneratedHeaderDropsToolBuildIdentity(t *testing.T) {
	for _, tc := range []struct {
		name   string
		header string
	}{
		{name: "go install build", header: "// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT."},
		{name: "bazel build without module info", header: "// Code generated by unknown module path version unknown version DO NOT EDIT."},
	} {
		t.Run(tc.name, func(t *testing.T) {
			in := "// Package genclient provides primitives.\n//\n" + tc.header + "\npackage genclient\n"
			got, err := canonicalizeGeneratedHeader([]byte(in))
			if err != nil {
				t.Fatalf("canonicalizeGeneratedHeader: %v", err)
			}
			want := "// Package genclient provides primitives.\n//\n" + generatedHeader + "\npackage genclient\n"
			if string(got) != want {
				t.Fatalf("got:\n%s\nwant:\n%s", got, want)
			}
		})
	}
}

func TestCanonicalizeGeneratedHeaderRejectsMissingOrDuplicateHeader(t *testing.T) {
	line := "// Code generated by x version y DO NOT EDIT.\n"
	for _, in := range []string{"package genclient\n", line + line + "package genclient\n"} {
		if _, err := canonicalizeGeneratedHeader([]byte(in)); err == nil {
			t.Errorf("canonicalizeGeneratedHeader(%q) succeeded, want error", in)
		}
	}
}

func TestGeneratedHeaderIsRecognizedAsGeneratedCode(t *testing.T) {
	if !strings.HasPrefix(generatedHeader, "// Code generated ") || !strings.HasSuffix(generatedHeader, " DO NOT EDIT.") {
		t.Fatalf("generatedHeader %q does not match the Go generated-code convention", generatedHeader)
	}
}
