package beads

import (
	"errors"
	"fmt"
	"time"
)

// Create passes through to the backing store and updates the cache.
func (c *CachingStore) Create(b Bead) (Bead, error) {
	return c.createWith(func() (Bead, error) {
		return c.backing.Create(b)
	})
}

// CreateWithStorage passes through a policy-selected storage class to backing
// stores that support table-specific creates, then updates the cache.
func (c *CachingStore) CreateWithStorage(b Bead, storage StorageClass) (Bead, error) {
	storageBacking, ok := c.backing.(StorageCreateStore)
	if !ok {
		return c.Create(b)
	}
	return c.createWith(func() (Bead, error) {
		return storageBacking.CreateWithStorage(b, storage)
	})
}

func (c *CachingStore) createWith(create func() (Bead, error)) (Bead, error) {
	// Create's concrete ID may be generated by the backing store. Holding the
	// shared scope excludes unknown multi-ID commits while allowing unrelated
	// known-ID writes and creates to proceed. Once Create returns, no same-cache
	// caller can yet know the generated ID, so acquiring its per-ID lock here is
	// sufficient to serialize refresh, cache finalization, and notification
	// reservation without putting this hot path under the global write lock.
	c.mutationScopeMu.RLock()
	created, err := create()
	if err != nil {
		c.mutationScopeMu.RUnlock()
		return created, err
	}
	ordered, locks, _ := c.reserveCloseStateLocks(created.ID)
	unlockID := c.lockReservedCloseState(ordered, locks)
	var drain func()
	defer func() {
		unlockID()
		c.mutationScopeMu.RUnlock()
		if drain != nil {
			drain()
		}
	}()

	if fresh, err := c.backing.Get(created.ID); err == nil {
		created = fresh
	} else if !errors.Is(err, ErrNotFound) {
		c.recordProblem("refresh bead after create", fmt.Errorf("%s: %w", created.ID, err))
	}

	c.mu.Lock()
	c.noteLocalMutationLocked(created.ID)
	c.absorbFreshLocked(created.ID, created, time.Now(), absorbOpts{
		depsMode:   depsFromFields,
		seqMode:    seqKeep,
		clearDirty: true,
	})
	c.markFreshLocked(time.Now())
	c.updateStatsLocked()
	c.mu.Unlock()

	drain, _ = c.enqueueOrderedChange("bead.created", created)
	return created, nil
}

// Update passes through to the backing store and refreshes the cache.
func (c *CachingStore) Update(id string, opts UpdateOpts) error {
	unlock := c.lockCloseState(id)
	var drain func()
	defer func() {
		unlock()
		if drain != nil {
			drain()
		}
	}()

	// Idempotence: if every non-nil field in opts already matches the
	// cached bead AND the cache is primed, the backing call is a no-op.
	// Skipping it avoids the bd subprocess invocation, the on_update
	// hook, and the post-update Get refresh — same payoff as the
	// SetMetadata short-circuit at metadataAlreadyMatchesCached.
	// See gastownhall/gascity#1978 Phase 1.
	statusClose := opts.Status != nil && *opts.Status == "closed"
	if !statusClose && c.updateMatchesCached(id, opts) {
		return nil
	}
	if statusClose {
		var err error
		if transitioner, ok := UpdateTransitionerFor(c.backing); ok {
			drain, err = c.updateStatusCloseWithTransition(id, opts, transitioner)
		} else {
			drain, err = c.updateStatusCloseWithoutTransition(id, opts)
		}
		return err
	}

	c.mu.RLock()
	previous, hadPrevious := c.beads[id]
	previous = cloneBead(previous)
	c.mu.RUnlock()
	if !hadPrevious {
		if freshPrevious, err := c.backing.Get(id); err == nil {
			previous = freshPrevious
			hadPrevious = true
		} else if !errors.Is(err, ErrNotFound) {
			c.recordProblem("snapshot bead before update", fmt.Errorf("%s: %w", id, err))
		}
	}
	if err := c.backing.Update(id, opts); err != nil {
		c.markMutationFailureDirty(id)
		if opts.Status != nil {
			c.mu.Lock()
			c.clearDependentReadyProjectionsLocked(id)
			c.updateStatsLocked()
			c.mu.Unlock()
		}
		return err
	}

	// Re-fetch a complete backing snapshot. A successful Update does not return
	// the row it committed, so a visibility-lagged read cannot be patched with
	// opts: doing so would attach locally inferred fields to a revision that
	// never carried them. Prefer a revision newer than the cached pre-write row.
	// Legacy exec-backed stores may not carry revisions, so accept a zero-revision
	// observation only when it visibly changed and the cached row has not changed
	// since the pre-write snapshot.
	fresh, deps, err := c.readBeadWithDeps(id)
	if err != nil {
		c.mu.Lock()
		c.noteLocalMutationLocked(id)
		current, ok := c.beads[id]
		if !ok && hadPrevious {
			current = previous
			ok = true
		}
		if ok {
			fresh = applyUpdateOptsToBead(current, opts)
			c.absorbFreshLocked(id, fresh, time.Now(), absorbOpts{
				depsMode:   depsFromFields,
				seqMode:    seqKeep,
				clearDirty: false,
			})
			if opts.Status != nil {
				c.clearDependentReadyProjectionsLocked(id)
			}
			c.markDirtyLocked(id)
			c.retainPendingPublication(id, "bead.updated")
			c.updateStatsLocked()
			c.mu.Unlock()
			if !errors.Is(err, ErrNotFound) {
				c.recordProblem("refresh bead after update", fmt.Errorf("%s: %w", id, err))
			}
			return nil
		}
		c.markDirtyLocked(id)
		// The cache never held this bead and had no pre-write snapshot: this Update
		// is its first observation. Retain hadRow=false so a reconcile-synthesized
		// creation edge survives instead of being erased by the recovered update.
		c.retainPendingPublicationHadRow(id, "bead.updated", false)
		c.mu.Unlock()
		if !errors.Is(err, ErrNotFound) {
			c.recordProblem("refresh bead after update", fmt.Errorf("%s: %w", id, err))
		}
		return nil
	}
	authoritativeObservation := false
	c.mu.Lock()
	c.noteLocalMutationLocked(id)
	current, hasCurrent := c.beads[id]
	_, currentlyDeleted := c.deletedSeq[id]
	newerRevision := hadPrevious && fresh.Revision > previous.Revision &&
		(!hasCurrent || current.Revision <= previous.Revision || fresh.Revision > current.Revision)
	revisionlessUpdate := hadPrevious && previous.Revision == 0 && fresh.Revision == 0 &&
		beadChanged(previous, fresh, false) &&
		(!hasCurrent || !beadChanged(current, previous, false))
	authoritativeObservation = !currentlyDeleted && (newerRevision || revisionlessUpdate)
	if authoritativeObservation {
		c.absorbFreshLocked(id, fresh, time.Now(), absorbOpts{
			depsMode:   depsExplicit,
			deps:       deps,
			seqMode:    seqKeep,
			clearDirty: true,
		})
	} else {
		if hadPrevious && !currentlyDeleted &&
			(!hasCurrent || current.Revision <= previous.Revision) && fresh.Revision <= previous.Revision {
			// Preserve read-your-write as a dirty local fallback while backing
			// visibility catches up. This row is never published and can never be
			// used for a fenced write: dirty reads must reconsult the backing.
			fallback := applyUpdateOptsToBead(fresh, opts)
			c.absorbFreshLocked(id, fallback, time.Now(), absorbOpts{
				depsMode:   depsExplicit,
				deps:       deps,
				seqMode:    seqKeep,
				clearDirty: false,
			})
		}
		c.markDirtyLocked(id)
		// hadPrevious carries whether this cache ever held the bead: without a
		// prior snapshot this non-authoritative update is a first observation, so a
		// later recovered creation edge must not be downgraded to an update.
		c.retainPendingPublicationHadRow(id, "bead.updated", hadPrevious)
	}
	if opts.Status != nil {
		c.clearDependentReadyProjectionsLocked(id)
	}
	if authoritativeObservation {
		c.markFreshLocked(time.Now())
	}
	c.updateStatsLocked()
	c.mu.Unlock()

	if authoritativeObservation {
		drain, _ = c.enqueueOrderedCompleteChange("bead.updated", fresh)
	}
	return nil
}

func (c *CachingStore) updateStatusCloseWithTransition(id string, opts UpdateOpts, transitioner UpdateTransitioner) (func(), error) {
	transition, updateErr := transitioner.UpdateWithTransition(id, opts)
	if !transition.AuthoritativeAfter(id) {
		if errors.Is(updateErr, ErrUpdateTransitionUnsupported) {
			return c.updateStatusCloseWithoutTransition(id, opts)
		}
		c.markMutationFailureDirty(id)
		if updateErr != nil {
			return nil, updateErr
		}
		return nil, fmt.Errorf("updating bead %q: atomic transition returned no authoritative after snapshot", id)
	}

	now := time.Now()
	c.mu.Lock()
	c.noteLocalMutationLocked(id)
	c.absorbFreshLocked(id, transition.After, now, absorbOpts{
		depsMode:   depsFromFields,
		seqMode:    seqKeep,
		clearDirty: true,
	})
	c.clearDependentReadyProjectionsLocked(id)
	c.markFreshLocked(now)
	c.updateStatsLocked()
	c.mu.Unlock()

	eventType := ""
	if transition.TransitionedToClosed {
		eventType = "bead.closed"
	} else if updateErr == nil || beadChanged(transition.Before, transition.After, false) {
		// A commit-acknowledgement error removes proof that this writer owned an
		// open-to-closed transition, but the authoritative After row may still
		// prove that durable state changed. Publish that truth conservatively so
		// observers do not remain behind a clean cache entry.
		eventType = "bead.updated"
	}
	if eventType == "" {
		return nil, updateErr
	}
	drain, _ := c.enqueueOrderedCompleteChange(eventType, transition.After)
	return drain, updateErr
}

func (c *CachingStore) updateStatusCloseWithoutTransition(id string, opts UpdateOpts) (func(), error) {
	if err := c.backing.Update(id, opts); err != nil {
		c.markMutationFailureDirty(id)
		return nil, err
	}

	fresh, deps, refreshErr := c.readBeadWithDeps(id)
	if refreshErr != nil {
		c.mu.Lock()
		seq := c.noteLocalMutationLocked(id)
		if errors.Is(refreshErr, ErrNotFound) {
			c.tombstoneLocked(id, seq)
			c.clearDependentReadyProjectionsLocked(id)
			// The close committed; only its refresh failed. Retain a close-shaped
			// intent so recovery reads the closed projection (a closed-hiding backing
			// hides the row from an ordinary Get) and publishes the close edge rather
			// than an update that type-driven consumers drop.
			c.retainPendingPublication(id, "bead.closed")
			c.markFreshLocked(time.Now())
			c.updateStatsLocked()
			c.mu.Unlock()
			return nil, nil
		}
		c.markDirtyLocked(id)
		c.clearDependentReadyProjectionsLocked(id)
		c.retainPendingPublication(id, "bead.closed")
		c.updateStatsLocked()
		c.mu.Unlock()
		c.recordProblem("refresh bead after update", fmt.Errorf("%s: %w", id, refreshErr))
		return nil, nil
	}

	now := time.Now()
	c.mu.Lock()
	c.noteLocalMutationLocked(id)
	c.absorbFreshLocked(id, fresh, now, absorbOpts{
		depsMode:   depsExplicit,
		deps:       deps,
		seqMode:    seqKeep,
		clearDirty: true,
	})
	c.clearDependentReadyProjectionsLocked(id)
	c.markFreshLocked(now)
	c.updateStatsLocked()
	c.mu.Unlock()
	// A successful capability-less status close is a committed close: publish the
	// close edge so eventexport and bead.closed order gates see it. Fall back to
	// bead.updated only if the authoritative refresh shows the row is no longer
	// closed (a peer reopened it after the close committed).
	eventType := "bead.updated"
	if fresh.Status == "closed" {
		eventType = "bead.closed"
	}
	drain, _ := c.enqueueOrderedCompleteChange(eventType, fresh)
	return drain, nil
}

// ReleaseIfCurrent clears an in-progress assignment through the backing store
// and refreshes the cache only when the conditional release succeeds.
func (c *CachingStore) ReleaseIfCurrent(id, expectedAssignee string) (bool, error) {
	unlock := c.lockCloseState(id)
	var drain func()
	defer func() {
		unlock()
		if drain != nil {
			drain()
		}
	}()

	releaser, ok := c.backing.(ConditionalAssignmentReleaser)
	if !ok {
		return false, ErrConditionalReleaseUnsupported
	}
	c.mu.RLock()
	previous, hadPrevious := c.beads[id]
	previous = cloneBead(previous)
	c.mu.RUnlock()
	if !hadPrevious {
		if freshPrevious, err := c.backing.Get(id); err == nil {
			previous = freshPrevious
			hadPrevious = true
		} else if !errors.Is(err, ErrNotFound) {
			c.recordProblem("snapshot bead before release-if-current", fmt.Errorf("%s: %w", id, err))
		}
	}
	released, err := releaser.ReleaseIfCurrent(id, expectedAssignee)
	if err != nil {
		c.markMutationFailureDirty(id)
		c.mu.Lock()
		c.clearDependentReadyProjectionsLocked(id)
		c.updateStatsLocked()
		c.mu.Unlock()
		return released, err
	}
	if !released {
		return released, err
	}

	fresh, deps, refreshed := c.refreshBeadWithDepsAfterWrite(id, "refresh bead after release-if-current")
	var updated Bead
	notify := false
	c.mu.Lock()
	c.noteLocalMutationLocked(id)
	if refreshed {
		current, hasCurrent := c.beads[id]
		_, currentlyDeleted := c.deletedSeq[id]
		newerThanKnown := hadPrevious && fresh.Revision > previous.Revision &&
			!currentlyDeleted && (!hasCurrent || current.Revision <= previous.Revision || fresh.Revision > current.Revision)
		if newerThanKnown {
			c.absorbFreshLocked(id, fresh, time.Now(), absorbOpts{
				depsMode:   depsExplicit,
				deps:       deps,
				seqMode:    seqKeep,
				clearDirty: true,
			})
			updated = cloneBead(fresh)
			notify = true
		} else {
			c.markDirtyLocked(id)
		}
	} else {
		c.markDirtyLocked(id)
	}
	if !notify {
		c.retainPendingPublication(id, "bead.updated")
	}
	c.clearDependentReadyProjectionsLocked(id)
	if notify {
		c.markFreshLocked(time.Now())
	}
	c.updateStatsLocked()
	c.mu.Unlock()
	if notify {
		drain, _ = c.enqueueOrderedCompleteChange("bead.updated", updated)
	}
	return true, nil
}

// beginCloseObserverSuppression fences each target before backing I/O and
// records operation-scoped observer suppression. The early fence prevents a
// reconciliation snapshot captured before this call from merging after the
// suppression ends; the suppression map covers snapshots captured while the
// close is in flight. Caller-visible close methods pair this with
// endCloseObserverSuppression via defer.
func (c *CachingStore) beginCloseObserverSuppression(ids ...string) {
	c.mu.Lock()
	defer c.mu.Unlock()

	c.noteLocalMutationLocked(ids...)
	if c.closeObserverSuppressions == nil {
		c.closeObserverSuppressions = make(map[string]int)
	}
	for _, id := range ids {
		if id != "" {
			c.closeObserverSuppressions[id]++
		}
	}
}

func (c *CachingStore) endCloseObserverSuppression(ids ...string) {
	c.mu.Lock()
	defer c.mu.Unlock()

	for _, id := range ids {
		if id == "" {
			continue
		}
		if c.closeObserverSuppressions[id] <= 1 {
			delete(c.closeObserverSuppressions, id)
			continue
		}
		c.closeObserverSuppressions[id]--
	}
}

// Close marks a bead as closed in the backing store and cache.
func (c *CachingStore) Close(id string) error {
	c.beginCloseObserverSuppression(id)
	defer c.endCloseObserverSuppression(id)

	if _, ok := CloseTransitionerFor(c.backing); ok {
		_, err := c.closeWithReasonIfOpen(id, "", true)
		if err == nil || !errors.Is(err, ErrCloseTransitionUnsupported) {
			return err
		}
	}
	return c.closeLegacy(id, true)
}

// CloseWithReasonIfOpen forwards the atomic close to the backing store, then
// installs the exact durable result in the cache. Observer callbacks run only
// after the cache lock is released so they may safely re-enter the store.
func (c *CachingStore) CloseWithReasonIfOpen(id, reason string) (CloseTransition, error) {
	c.beginCloseObserverSuppression(id)
	defer c.endCloseObserverSuppression(id)

	return c.closeWithReasonIfOpen(id, reason, true)
}

// CloseWithoutObserver performs the same durable close and cache update as
// Close while suppressing this cache's bead.closed observer callback for this
// operation only. It is used when a caller must preserve a legacy close but
// cannot prove ownership of the open-to-closed transition. Suppression is an
// argument on this call rather than shared state, so concurrent writes retain
// their normal notifications.
func (c *CachingStore) CloseWithoutObserver(id string) error {
	c.beginCloseObserverSuppression(id)
	defer c.endCloseObserverSuppression(id)

	if _, ok := CloseTransitionerFor(c.backing); ok {
		_, err := c.closeWithReasonIfOpen(id, "", false)
		if err == nil || !errors.Is(err, ErrCloseTransitionUnsupported) {
			return err
		}
	}
	return c.closeLegacy(id, false)
}

// CloseWithoutObserverWithDelivery performs the same suppressed close as
// CloseWithoutObserver and returns a nonblocking receipt for the close's place
// in the same-ID observer order. The receipt publishes nothing itself; it is
// for callers that own an at-least-once replacement notification.
func (c *CachingStore) CloseWithoutObserverWithDelivery(id string) (CloseObserverDelivery, error) {
	c.beginCloseObserverSuppression(id)
	defer c.endCloseObserverSuppression(id)

	if _, ok := CloseTransitionerFor(c.backing); ok {
		_, delivery, err := c.closeWithReasonIfOpenSequenced(id, "", false, true)
		if err == nil || !errors.Is(err, ErrCloseTransitionUnsupported) {
			return delivery, err
		}
	}
	return c.closeLegacySequenced(id, false, true)
}

// BeadObserverBarrier reserves a non-mutating position in this cache's
// same-bead observer queue. It takes the same per-bead mutation lock as writes,
// so notifications from mutations that completed first are guaranteed to be
// delivered before the receipt. The mutation lock is released before any
// queue draining or receipt callback runs, preserving observer reentrancy.
func (c *CachingStore) BeadObserverBarrier(id string) CloseObserverDelivery {
	unlock := c.lockCloseState(id)
	drain, delivery := c.enqueueOrderedBarrier(id)
	unlock()
	if drain != nil {
		drain()
	}
	return delivery
}

func (c *CachingStore) closeWithReasonIfOpen(id, reason string, notifyObserver bool) (CloseTransition, error) {
	transition, _, err := c.closeWithReasonIfOpenSequenced(id, reason, notifyObserver, false)
	return transition, err
}

func (c *CachingStore) closeWithReasonIfOpenSequenced(id, reason string, notifyObserver, sequenceSuppressed bool) (CloseTransition, CloseObserverDelivery, error) {
	closer, ok := CloseTransitionerFor(c.backing)
	if !ok {
		return CloseTransition{}, nil, ErrCloseTransitionUnsupported
	}
	unlock := c.lockCloseState(id)

	transition, err := closer.CloseWithReasonIfOpen(id, reason)
	if err != nil && !transition.AuthoritativeClosed(id) {
		// The backing may have committed before returning any error. Bump the
		// mutation sequence as well as marking dirty so a scan started during
		// the write cannot merge its stale row back as clean.
		c.mu.Lock()
		c.noteLocalMutationLocked(id)
		c.markDirtyLocked(id)
		c.mu.Unlock()
		unlock()
		return transition, nil, err
	}

	now := time.Now()
	c.mu.Lock()
	c.noteLocalMutationLocked(id)
	c.absorbFreshLocked(id, transition.After, now, absorbOpts{
		depsMode:   depsFromFields,
		seqMode:    seqKeep,
		clearDirty: true,
	})
	c.clearDependentReadyProjectionsLocked(id)
	c.markFreshLocked(now)
	c.updateStatsLocked()
	c.mu.Unlock()
	var (
		drain            func()
		ownDelivery      *cacheObserverDelivery
		ownCloseDelivery bool
	)
	if notifyObserver && !transition.ObserverNotified && transition.ObserverDelivery == nil {
		if transition.Transitioned {
			drain, ownDelivery = c.enqueueOrderedCompleteChange("bead.closed", transition.After)
			transition.ObserverDelivery = ownDelivery
			ownCloseDelivery = true
		} else if beadChanged(transition.Before, transition.After, false) {
			// An authoritative changed row without transition ownership cannot be
			// called bead.closed. A conservative update still advances snapshot
			// consumers after an ambiguous commit acknowledgement.
			drain, ownDelivery = c.enqueueOrderedCompleteChange("bead.updated", transition.After)
		}
	} else if sequenceSuppressed {
		drain, ownDelivery = c.enqueueOrderedBarrier(id)
	}
	unlock()
	if drain != nil {
		drain()
	}
	if ownCloseDelivery && ownDelivery.isDelivered() {
		transition.ObserverNotified = true
	}
	return transition, ownDelivery, err
}

// closeLegacy preserves unconditional Close support for backings that cannot
// prove transition ownership. A failed refresh may synthesize the closed
// status for the local cache, but the row stays dirty because its revision is
// not authoritative; the next read must converge with the backing store. Only
// an exact post-write read may leave the cache as an observer notification.
func (c *CachingStore) closeLegacy(id string, notifyObserver bool) error {
	_, err := c.closeLegacySequenced(id, notifyObserver, false)
	return err
}

func (c *CachingStore) closeLegacySequenced(id string, notifyObserver, sequenceSuppressed bool) (CloseObserverDelivery, error) {
	unlock := c.lockCloseState(id)

	// Idempotence: if the cached bead status is already "closed" AND the
	// cache is primed, the backing call is a no-op. Skipping it avoids
	// the bd subprocess invocation, the on_update hook, and the
	// post-close Get refresh. See gastownhall/gascity#1978 Phase 1.
	if c.closeAlreadyMatchesCached(id) {
		var drain func()
		var delivery *cacheObserverDelivery
		if sequenceSuppressed {
			drain, delivery = c.enqueueOrderedBarrier(id)
		}
		unlock()
		if drain != nil {
			drain()
		}
		return delivery, nil
	}
	if err := c.backing.Close(id); err != nil {
		c.markMutationFailureDirty(id)
		unlock()
		return nil, err
	}

	// Adopt the successful refresh read: it carries the post-close revision,
	// which Get→conditional-write consumers fence against — patching only the
	// cached entry's status would keep serving the pre-close revision forever.
	// Do not force the status returned by Get. Another writer may have reopened
	// the bead after Close committed; rewriting that exact observation as closed
	// would put observer projections behind durable state.
	var closed Bead
	var found bool
	var refreshed bool
	if fresh, _, err := c.readBeadWithDeps(id); err == nil {
		closed = fresh
		found = true
		refreshed = true
	} else if !errors.Is(err, ErrNotFound) {
		c.recordProblem("refresh bead after close", fmt.Errorf("%s: %w", id, err))
	}

	c.mu.Lock()
	c.noteLocalMutationLocked(id)
	if refreshed {
		c.absorbFreshLocked(id, closed, time.Now(), absorbOpts{
			depsMode:   depsFromFields,
			seqMode:    seqKeep,
			clearDirty: true,
		})
	} else if b, ok := c.beads[id]; ok {
		b.Status = "closed"
		c.absorbFreshLocked(id, b, time.Now(), absorbOpts{
			depsMode:   depsKeepCached,
			seqMode:    seqKeep,
			clearDirty: false,
		})
		c.markDirtyLocked(id)
		closed = cloneBead(b)
		found = true
	} else {
		c.markDirtyLocked(id)
	}
	if notifyObserver && !refreshed {
		// The backing Close committed but its refresh could not be read. Retain a
		// close-shaped intent so recovery consults the closed projection (a
		// closed-hiding backing hides the row from an ordinary Get) and delivers the
		// close edge rather than an update that type-driven consumers drop.
		c.retainPendingPublication(id, "bead.closed")
	}
	dependentProjectionCleared := false
	if !refreshed || closed.Status == "closed" {
		dependentProjectionCleared = c.clearDependentReadyProjectionsLocked(id)
	}
	if found || dependentProjectionCleared {
		c.markFreshLocked(time.Now())
		c.updateStatsLocked()
	}
	c.mu.Unlock()
	var (
		drain    func()
		delivery *cacheObserverDelivery
	)
	if notifyObserver && refreshed {
		// A successful legacy Close is a committed close: publish the close edge so
		// eventexport and bead.closed order gates observe it, carrying the complete
		// refreshed row. Fall back to bead.updated only when the authoritative
		// refresh shows a non-closed row (a peer reopened it after Close committed),
		// which must not be published as a close.
		eventType := "bead.updated"
		if closed.Status == "closed" {
			eventType = "bead.closed"
		}
		drain, delivery = c.enqueueOrderedCompleteChange(eventType, closed)
	} else if sequenceSuppressed {
		drain, delivery = c.enqueueOrderedBarrier(id)
	}
	unlock()
	if drain != nil {
		drain()
	}
	return delivery, nil
}

// Reopen marks a bead as open in the backing store and cache.
func (c *CachingStore) Reopen(id string) error {
	unlock := c.lockCloseState(id)
	if err := c.backing.Reopen(id); err != nil {
		c.markMutationFailureDirty(id)
		unlock()
		return err
	}

	// Adopt and publish only the exact successful refresh read. Another writer
	// may have closed the bead again after Reopen committed, so forcing the
	// observed row open would fabricate a snapshot at the returned revision.
	var reopened Bead
	var found bool
	var refreshed bool
	if fresh, _, err := c.readBeadWithDeps(id); err == nil {
		reopened = fresh
		found = true
		refreshed = true
	} else if !errors.Is(err, ErrNotFound) {
		c.recordProblem("refresh bead after reopen", fmt.Errorf("%s: %w", id, err))
	}

	c.mu.Lock()
	c.noteLocalMutationLocked(id)
	if refreshed {
		c.absorbFreshLocked(id, reopened, time.Now(), absorbOpts{
			depsMode:   depsFromFields,
			seqMode:    seqKeep,
			clearDirty: true,
		})
	} else if b, ok := c.beads[id]; ok {
		b.Status = "open"
		c.absorbFreshLocked(id, b, time.Now(), absorbOpts{
			depsMode:   depsKeepCached,
			seqMode:    seqKeep,
			clearDirty: false,
		})
		c.markDirtyLocked(id)
		found = true
	} else {
		c.markDirtyLocked(id)
	}
	if !refreshed {
		c.retainPendingPublication(id, "bead.updated")
	}
	dependentProjectionCleared := c.clearDependentReadyProjectionsLocked(id)
	if found || dependentProjectionCleared {
		c.markFreshLocked(time.Now())
		c.updateStatsLocked()
	}
	c.mu.Unlock()
	var drain func()
	if refreshed {
		drain, _ = c.enqueueOrderedCompleteChange("bead.updated", reopened)
	}
	unlock()
	if drain != nil {
		drain()
	}
	return nil
}

// CloseAll closes multiple beads and sets metadata on each.
func (c *CachingStore) CloseAll(ids []string, metadata map[string]string) (int, error) {
	c.beginCloseObserverSuppression(ids...)
	defer c.endCloseObserverSuppression(ids...)

	return c.closeAll(ids, metadata, true)
}

// CloseAllWithoutObserver performs the same durable batch close and cache
// refresh as CloseAll while suppressing this cache's bead.closed observer
// callbacks for this operation only. See CloseWithoutObserver.
func (c *CachingStore) CloseAllWithoutObserver(ids []string, metadata map[string]string) (int, error) {
	c.beginCloseObserverSuppression(ids...)
	defer c.endCloseObserverSuppression(ids...)

	return c.closeAll(ids, metadata, false)
}

func (c *CachingStore) closeAll(ids []string, metadata map[string]string, notifyObserver bool) (int, error) {
	unlock := c.lockCloseState(ids...)
	if transitioner, ok := CloseAllTransitionerFor(c.backing); ok {
		result, err := transitioner.CloseAllWithTransitions(ids, metadata)
		if !errors.Is(err, ErrCloseAllTransitionUnsupported) {
			drains := c.installCloseAllTransitions(ids, result, notifyObserver)
			unlock()
			for _, drain := range drains {
				drain()
			}
			return result.Count, err
		}
	}

	n, drains, err := c.closeAllLegacy(ids, metadata, notifyObserver)
	unlock()
	for _, drain := range drains {
		drain()
	}
	return n, err
}

// installCloseAllTransitions adopts only complete backing-owned snapshots and
// publishes only explicit live-to-closed ownership proofs. IDs are deduplicated
// independently of the backing count: individual backends retain their own
// duplicate-ID count semantics, while one per-ID transition can update and
// notify this cache at most once.
func (c *CachingStore) installCloseAllTransitions(ids []string, result CloseAllTransitionResult, notifyObserver bool) []func() {
	unique := make(map[string]struct{}, len(ids))
	notifications := make([]cacheNotification, 0, len(result.Transitions))
	now := time.Now()

	c.mu.Lock()
	c.noteLocalMutationLocked(ids...)
	for _, id := range ids {
		if id == "" {
			continue
		}
		if _, seen := unique[id]; seen {
			continue
		}
		unique[id] = struct{}{}

		transition, authoritative := result.TransitionFor(id)
		if !authoritative {
			c.markDirtyLocked(id)
			continue
		}

		opts := absorbOpts{depsMode: depsFromFields, seqMode: seqKeep, clearDirty: true}
		if transition.After.Status == "closed" {
			opts.depsMode = depsDrop
		}
		c.absorbFreshLocked(id, transition.After, now, opts)
		if transition.After.Status == "closed" {
			c.clearDependentReadyProjectionsLocked(id)
		}
		if transition.Transitioned && transition.Before.Status != "closed" && transition.After.Status == "closed" {
			notifications = append(notifications, cacheNotification{
				eventType:      "bead.closed",
				bead:           cloneBead(transition.After),
				resolvePending: true,
			})
		} else if beadChanged(transition.Before, transition.After, false) {
			notifications = append(notifications, cacheNotification{
				eventType:      "bead.updated",
				bead:           cloneBead(transition.After),
				resolvePending: true,
			})
		}
	}
	c.markFreshLocked(now)
	c.updateStatsLocked()
	c.mu.Unlock()

	if !notifyObserver {
		return nil
	}
	drains := make([]func(), 0, len(notifications))
	for _, notification := range notifications {
		if drain, _ := c.enqueueOrderedCompleteChange(notification.eventType, notification.bead); drain != nil {
			drains = append(drains, drain)
		}
	}
	return drains
}

// closeAllLegacy preserves refresh-based cache convergence for stores without
// the backing transition capability. A post-write Get is an authoritative
// observation, but it cannot prove which writer owned a lifecycle transition,
// so this path publishes bead.updated rather than bead.closed.
func (c *CachingStore) closeAllLegacy(ids []string, metadata map[string]string, notifyObserver bool) (int, []func(), error) {
	n, err := c.backing.CloseAll(ids, metadata)
	if err != nil && n == 0 {
		c.markMutationFailureDirty(ids...)
		return n, nil, err
	}

	// A single unique requested ID with n == 1 is proven committed even when the
	// backing returns an ancillary error: the count identifies the one target
	// unambiguously. Multi-ID count-only failures cannot say which IDs committed,
	// so they stay on the err == nil retention rule below.
	uniqueRequested := make(map[string]struct{}, len(ids))
	for _, id := range ids {
		if id != "" {
			uniqueRequested[id] = struct{}{}
		}
	}
	singleProvenCommit := len(uniqueRequested) == 1 && n == 1

	type refreshedBead struct {
		id   string
		bead Bead
	}
	refreshed := make([]refreshedBead, 0, len(ids))
	var refreshErr error
	refreshFailed := make(map[string]struct{})
	seen := make(map[string]struct{}, len(ids))
	for _, id := range ids {
		if id == "" {
			continue
		}
		if _, duplicate := seen[id]; duplicate {
			continue
		}
		seen[id] = struct{}{}
		fresh, _, getErr := c.readBeadWithDeps(id)
		if getErr != nil {
			refreshFailed[id] = struct{}{}
			refreshErr = errors.Join(refreshErr, fmt.Errorf("refresh bead after close-all %s: %w", id, getErr))
			continue
		}
		refreshed = append(refreshed, refreshedBead{id: id, bead: fresh})
	}

	c.mu.Lock()
	c.noteLocalMutationLocked(ids...)
	if refreshErr != nil {
		c.recordProblemLocked("close-all refresh", refreshErr)
	}
	for id := range refreshFailed {
		c.markDirtyLocked(id)
		if notifyObserver && (err == nil || singleProvenCommit) {
			// A nil backing error identifies every requested ID as a completed
			// legacy batch target. A single-ID batch that reported n == 1 is
			// likewise proven committed even alongside an ancillary error. Both
			// cases retain intent; multi-ID count-only partial failures cannot
			// safely say which IDs committed, so they deliberately retain none.
			// A committed close whose refresh failed retains a close-shaped intent so
			// recovery reads the closed projection and delivers the close edge.
			c.retainPendingPublication(id, "bead.closed")
		}
	}
	for _, item := range refreshed {
		opts := absorbOpts{depsMode: depsFromFields, seqMode: seqKeep, clearDirty: true}
		if item.bead.Status == "closed" {
			opts.depsMode = depsDrop
		}
		c.absorbFreshLocked(item.id, item.bead, time.Now(), opts)
		if item.bead.Status == "closed" {
			c.clearDependentReadyProjectionsLocked(item.id)
		}
	}
	c.markFreshLocked(time.Now())
	c.updateStatsLocked()
	c.mu.Unlock()

	if !notifyObserver {
		return n, nil, errors.Join(err, refreshErr)
	}
	drains := make([]func(), 0, len(refreshed))
	for _, item := range refreshed {
		// A successful legacy CloseAll is a committed close: publish the close edge
		// with the complete refreshed row. Fall back to bead.updated only when the
		// authoritative refresh shows a non-closed row (a peer reopened it after the
		// batch close committed).
		eventType := "bead.updated"
		if item.bead.Status == "closed" {
			eventType = "bead.closed"
		}
		if drain, _ := c.enqueueOrderedCompleteChange(eventType, item.bead); drain != nil {
			drains = append(drains, drain)
		}
	}
	return n, drains, errors.Join(err, refreshErr)
}

// markMutationFailureDirty fences and dirties every possible target after an
// ambiguous unconditional mutation failure. These APIs cannot prove that no
// durable write landed: a transport can fail after commit, and a batch may
// partially apply before reporting an error. The next Get must reconcile with
// backing storage rather than serve a clean pre-attempt row.
func (c *CachingStore) markMutationFailureDirty(ids ...string) {
	c.mu.Lock()
	defer c.mu.Unlock()

	c.noteLocalMutationLocked(ids...)
	for _, id := range ids {
		if id != "" {
			c.markDirtyLocked(id)
		}
	}
}

// SetMetadata sets a single metadata key-value on a bead.
func (c *CachingStore) SetMetadata(id, key, value string) error {
	unlock := c.lockCloseState(id)
	var drain func()
	defer func() {
		unlock()
		if drain != nil {
			drain()
		}
	}()

	// Idempotence: if the cached bead already has metadata[key] == value,
	// the backing call is a no-op semantically. Skipping it avoids the
	// bd subprocess invocation and — crucially — avoids firing bd's
	// on_update hook, which calls "gc event emit bead.updated" and
	// appends a line to the city's events.jsonl. Reconciler tick logic
	// repeatedly writes the same heartbeat / deferral fields every ~2s,
	// producing thousands of no-op events per hour. The cache is the
	// supervisor's authoritative read source, so a value-match here is
	// a value-match in the store.
	if c.metadataAlreadyMatchesCached(id, map[string]string{key: value}) {
		return nil
	}
	if err := c.backing.SetMetadata(id, key, value); err != nil {
		c.markMutationFailureDirty(id)
		return err
	}

	fresh, deps, refreshed := c.refreshBeadWithDepsAfterWrite(id, "refresh bead after metadata")
	var updated Bead
	notify := false
	c.mu.Lock()
	c.noteLocalMutationLocked(id)
	if refreshed {
		c.absorbFreshLocked(id, fresh, time.Now(), absorbOpts{
			depsMode:   depsExplicit,
			deps:       deps,
			seqMode:    seqKeep,
			clearDirty: true,
		})
		updated = cloneBead(fresh)
		notify = true
	} else if b, ok := c.beads[id]; ok {
		if b.Metadata == nil {
			b.Metadata = make(map[string]string)
		}
		b.Metadata[key] = value
		c.absorbFreshLocked(id, b, time.Now(), absorbOpts{
			depsMode:   depsKeepCached,
			seqMode:    seqKeep,
			clearDirty: false,
		})
		c.markDirtyLocked(id)
	} else {
		c.markDirtyLocked(id)
	}
	if !refreshed {
		c.retainPendingPublication(id, "bead.updated")
	}
	c.markFreshLocked(time.Now())
	c.updateStatsLocked()
	c.mu.Unlock()
	if notify {
		drain, _ = c.enqueueOrderedCompleteChange("bead.updated", updated)
	}
	return nil
}

// SetMetadataBatch sets multiple metadata key-values on a bead.
func (c *CachingStore) SetMetadataBatch(id string, kvs map[string]string) error {
	if len(kvs) == 0 {
		return nil
	}
	unlock := c.lockCloseState(id)
	var drain func()
	defer func() {
		unlock()
		if drain != nil {
			drain()
		}
	}()

	// Idempotence: see SetMetadata. If every kv pair already matches the
	// cached bead's metadata, skip the backing write — no bd subprocess,
	// no on_update hook fire, no events.jsonl entry. Reconciler ticks
	// re-stamp deferral timestamps and other "I observed this" markers
	// on every cycle; without this guard each cycle generates a
	// bead.updated event even when nothing changed.
	if c.metadataAlreadyMatchesCached(id, kvs) {
		return nil
	}
	if err := c.backing.SetMetadataBatch(id, kvs); err != nil {
		c.markMutationFailureDirty(id)
		return err
	}

	fresh, deps, refreshed := c.refreshBeadWithDepsAfterWrite(id, "refresh bead after metadata batch")
	var updated Bead
	notify := false
	c.mu.Lock()
	c.noteLocalMutationLocked(id)
	if refreshed {
		c.absorbFreshLocked(id, fresh, time.Now(), absorbOpts{
			depsMode:   depsExplicit,
			deps:       deps,
			seqMode:    seqKeep,
			clearDirty: true,
		})
		updated = cloneBead(fresh)
		notify = true
	} else if b, ok := c.beads[id]; ok {
		if b.Metadata == nil {
			b.Metadata = make(map[string]string, len(kvs))
		}
		for k, v := range kvs {
			b.Metadata[k] = v
		}
		c.absorbFreshLocked(id, b, time.Now(), absorbOpts{
			depsMode:   depsKeepCached,
			seqMode:    seqKeep,
			clearDirty: false,
		})
		c.markDirtyLocked(id)
	} else {
		c.markDirtyLocked(id)
	}
	if !refreshed {
		c.retainPendingPublication(id, "bead.updated")
	}
	c.markFreshLocked(time.Now())
	c.updateStatsLocked()
	c.mu.Unlock()
	if notify {
		drain, _ = c.enqueueOrderedCompleteChange("bead.updated", updated)
	}
	return nil
}

// readBeadWithDeps assembles one complete replacement snapshot. Store.Get is
// not required to carry dependency edges, so any observer event that replaces
// a projection row must pair it with DepList. If either read fails, callers may
// keep a dirty local fallback but must not publish a partial snapshot.
func (c *CachingStore) readBeadWithDeps(id string) (Bead, []Dep, error) {
	fresh, err := c.backing.Get(id)
	if err != nil {
		return Bead{}, nil, err
	}
	deps, err := c.backing.DepList(id, "down")
	if err != nil {
		return Bead{}, nil, err
	}
	fresh.Dependencies = cloneDeps(deps)
	fresh.Needs = nil
	return fresh, cloneDeps(deps), nil
}

func (c *CachingStore) refreshBeadWithDepsAfterWrite(id, op string) (Bead, []Dep, bool) {
	fresh, deps, err := c.readBeadWithDeps(id)
	if err != nil {
		c.recordProblem(op, fmt.Errorf("%s: %w", id, err))
		return Bead{}, nil, false
	}
	return fresh, deps, true
}

// Tx executes fn through the backing store transaction and refreshes touched
// cache entries after a successful commit.
func (c *CachingStore) Tx(commitMsg string, fn func(Tx) error) error {
	if fn == nil {
		return errors.New("beads tx: nil callback")
	}
	unlock := c.lockUnknownMutationScope()
	var drains []func()
	defer func() {
		unlock()
		for _, drain := range drains {
			drain()
		}
	}()

	tx := newCachingStoreTx()
	if err := c.backing.Tx(commitMsg, func(backingTx Tx) error {
		tx.backing = backingTx
		return fn(tx)
	}); err != nil {
		if !StoreSupportsAtomicTx(c.backing) {
			c.fenceFailedTx(tx.ids, tx.closed)
		}
		return err
	}
	drains = c.refreshTxTouchedBeads(tx.ids, tx.closed, tx.created)
	return nil
}

// AtomicTx reports whether Tx is atomic, which for the caching store is exactly
// whether its backing store provides an atomic transaction: CachingStore.Tx is a
// transparent pass-through to backing.Tx, so it inherits the backing's
// all-or-nothing (or partial-write) failure semantics.
func (c *CachingStore) AtomicTx() bool { return StoreSupportsAtomicTx(c.backing) }

type cachingStoreTx struct {
	backing Tx
	seen    map[string]struct{}
	closed  map[string]struct{}
	created map[string]struct{}
	ids     []string
}

func newCachingStoreTx() *cachingStoreTx {
	return &cachingStoreTx{
		seen:    make(map[string]struct{}),
		closed:  make(map[string]struct{}),
		created: make(map[string]struct{}),
	}
}

func (tx *cachingStoreTx) Create(b Bead) (Bead, error) {
	created, err := tx.backing.Create(b)
	if created.ID != "" {
		tx.touch(created.ID)
		if err == nil {
			tx.created[created.ID] = struct{}{}
		}
	}
	return created, err
}

func (tx *cachingStoreTx) Update(id string, opts UpdateOpts) error {
	tx.touch(id)
	if err := tx.backing.Update(id, opts); err != nil {
		return err
	}
	return nil
}

func (tx *cachingStoreTx) SetMetadataBatch(id string, kvs map[string]string) error {
	if len(kvs) == 0 {
		return nil
	}
	tx.touch(id)
	if err := tx.backing.SetMetadataBatch(id, kvs); err != nil {
		return err
	}
	return nil
}

func (tx *cachingStoreTx) Close(id string) error {
	tx.touch(id)
	tx.closed[id] = struct{}{}
	if err := tx.backing.Close(id); err != nil {
		return err
	}
	return nil
}

func (tx *cachingStoreTx) touch(id string) {
	if id == "" {
		return
	}
	if _, ok := tx.seen[id]; ok {
		return
	}
	tx.seen[id] = struct{}{}
	tx.ids = append(tx.ids, id)
}

type txTouchedBead struct {
	id      string
	bead    Bead
	found   bool
	closed  bool
	created bool
	err     error
}

func (c *CachingStore) fenceFailedTx(ids []string, closed map[string]struct{}) {
	if len(ids) == 0 {
		return
	}
	c.mu.Lock()
	defer c.mu.Unlock()
	c.noteLocalMutationLocked(ids...)
	for _, id := range ids {
		c.markDirtyLocked(id)
		if _, wasClosed := closed[id]; wasClosed {
			c.clearDependentReadyProjectionsLocked(id)
		}
	}
	c.updateStatsLocked()
}

func (c *CachingStore) refreshTxTouchedBeads(ids []string, closed, created map[string]struct{}) []func() {
	if len(ids) == 0 {
		return nil
	}

	refreshed := make([]txTouchedBead, 0, len(ids))
	var refreshErr error
	for _, id := range ids {
		_, wasClosed := closed[id]
		_, wasCreated := created[id]
		fresh, _, err := c.readBeadWithDeps(id)
		item := txTouchedBead{id: id, closed: wasClosed, created: wasCreated, err: err}
		if err == nil {
			item.bead = fresh
			item.found = true
		} else if !wasClosed || !errors.Is(err, ErrNotFound) {
			refreshErr = errors.Join(refreshErr, fmt.Errorf("refresh bead after tx %s: %w", id, err))
		}
		refreshed = append(refreshed, item)
	}

	notifications := make([]cacheNotification, 0, len(refreshed))
	now := time.Now()
	c.mu.Lock()
	c.noteLocalMutationLocked(ids...)
	if refreshErr != nil {
		c.recordProblemLocked("tx refresh", refreshErr)
	}
	for _, item := range refreshed {
		if item.found {
			previous, hadPrevious := c.beads[item.id]
			fresh := cloneBead(item.bead)
			closedObservation := fresh.Status == "closed" &&
				(item.closed || hadPrevious && previous.Status != "closed")
			statusChanged := closedObservation
			if hadPrevious && previous.Status != fresh.Status {
				statusChanged = true
			}
			c.absorbFreshLocked(item.id, fresh, now, absorbOpts{
				depsMode:   depsFromFields,
				seqMode:    seqKeep,
				clearDirty: true,
			})
			if statusChanged {
				c.clearDependentReadyProjectionsLocked(item.id)
			}
			// Tx.Close returns no authoritative before/after result. The refreshed
			// row is safe to publish, but an attempted close cannot establish that
			// this writer owned an open-to-closed transition.
			eventType := "bead.updated"
			if item.created {
				eventType = "bead.created"
			}
			if item.created || !hadPrevious || beadChanged(previous, fresh, false) || closedObservation {
				notifications = append(notifications, cacheNotification{
					eventType:      eventType,
					bead:           cloneBead(fresh),
					resolvePending: true,
				})
			}
			continue
		}
		if item.err != nil {
			c.markDirtyLocked(item.id)
			if item.closed {
				c.clearDependentReadyProjectionsLocked(item.id)
			}
			// The tx committed; only the post-commit refresh failed. A committed
			// close retains a close-shaped intent so recovery reads the closed
			// projection and publishes the close edge instead of an update that
			// type-driven consumers drop.
			eventType := "bead.updated"
			switch {
			case item.created:
				eventType = "bead.created"
			case item.closed:
				eventType = "bead.closed"
			}
			c.retainPendingPublication(item.id, eventType)
		}
	}
	c.markFreshLocked(now)
	c.updateStatsLocked()
	c.mu.Unlock()

	return c.enqueueOrderedChanges(notifications)
}

// updateMatchesCached returns true when every non-nil field in opts already
// reflects the cached bead's state AND the cache is primed. Returns false on
// cache miss, uninitialized cache, or any field mismatch — in which case the
// caller falls through to the backing write. Companion to
// metadataAlreadyMatchesCached but covers the full UpdateOpts surface
// (Title, Status, Type, Priority, Description, ParentID, Assignee, Metadata,
// Labels, RemoveLabels). See gastownhall/gascity#1978 Phase 1.
//
// The short-circuit path skips the deduplication that
// applyUpdateOptsToBead performs on the non-short-circuit pass. Cached
// bead labels come from bd/dolt's canonical state, which never produces
// duplicates, so a Labels-equal match here is a Labels-equal match in
// the store after applyUpdateOptsToBead would have run. If a future
// path injects duplicate labels into the cache, this short-circuit
// would skip the dedup-fixup — file an issue rather than relaxing the
// invariant here.
func (c *CachingStore) updateMatchesCached(id string, opts UpdateOpts) bool {
	if id == "" {
		return false
	}
	c.mu.RLock()
	defer c.mu.RUnlock()
	if c.state != cacheLive && c.state != cachePartial {
		return false
	}
	if _, dirty := c.dirty[id]; dirty {
		return false
	}
	b, ok := c.beads[id]
	if !ok {
		return false
	}
	if opts.Title != nil && b.Title != *opts.Title {
		return false
	}
	if opts.Status != nil && b.Status != *opts.Status {
		return false
	}
	if opts.Type != nil && b.Type != *opts.Type {
		return false
	}
	if opts.Priority != nil {
		if b.Priority == nil || *b.Priority != *opts.Priority {
			return false
		}
	}
	if opts.Description != nil && b.Description != *opts.Description {
		return false
	}
	if opts.ParentID != nil && b.ParentID != *opts.ParentID {
		return false
	}
	if opts.Assignee != nil && b.Assignee != *opts.Assignee {
		return false
	}
	for k, v := range opts.Metadata {
		if b.Metadata == nil {
			if v != "" {
				return false
			}
			continue
		}
		if b.Metadata[k] != v {
			return false
		}
	}
	if len(opts.Labels) > 0 || len(opts.RemoveLabels) > 0 {
		// Set-equality check: opts.Labels ⊆ existing AND
		// (opts.RemoveLabels ∩ existing) = ∅ implies the final label set
		// after applyUpdateOptsToBead equals the current set. We skip
		// that function's dedup pass here — see the doc comment above
		// for why that's safe under bd/dolt's canonical labels.
		existing := make(map[string]struct{}, len(b.Labels))
		for _, l := range b.Labels {
			existing[l] = struct{}{}
		}
		for _, l := range opts.Labels {
			if _, present := existing[l]; !present {
				return false
			}
		}
		for _, l := range opts.RemoveLabels {
			if _, present := existing[l]; present {
				return false
			}
		}
	}
	return true
}

// closeAlreadyMatchesCached returns true when the cached bead status is
// already "closed" AND the cache is primed. Returns false on cache miss or
// uninitialized cache. See gastownhall/gascity#1978 Phase 1.
func (c *CachingStore) closeAlreadyMatchesCached(id string) bool {
	if id == "" {
		return false
	}
	c.mu.RLock()
	defer c.mu.RUnlock()
	if c.state != cacheLive && c.state != cachePartial {
		return false
	}
	if _, dirty := c.dirty[id]; dirty {
		return false
	}
	b, ok := c.beads[id]
	if !ok {
		return false
	}
	return b.Status == "closed"
}

// metadataAlreadyMatchesCached returns true when the cache holds a primed
// copy of the bead and every key/value in kvs is already present with the
// same value. A cache miss returns false (we cannot prove no-op), so the
// caller falls through to the backing write. Empty maps (no keys) match
// trivially, but callers should handle len==0 explicitly to avoid acquiring
// the lock for a guaranteed no-op.
func (c *CachingStore) metadataAlreadyMatchesCached(id string, kvs map[string]string) bool {
	if id == "" {
		return false
	}
	c.mu.RLock()
	defer c.mu.RUnlock()
	if c.state != cacheLive && c.state != cachePartial {
		return false
	}
	if _, dirty := c.dirty[id]; dirty {
		return false
	}
	b, ok := c.beads[id]
	if !ok {
		return false
	}
	if b.Metadata == nil {
		// Cache has the bead but no metadata map — any non-empty value
		// would be a write; an empty value (clearing a never-set key)
		// is already the desired state.
		for _, v := range kvs {
			if v != "" {
				return false
			}
		}
		return true
	}
	for k, v := range kvs {
		if b.Metadata[k] != v {
			return false
		}
	}
	return true
}

// DepAdd adds a dependency and updates the cache.
func (c *CachingStore) DepAdd(issueID, dependsOnID, depType string) error {
	unlock := c.lockCloseState(issueID)
	var drain func()
	defer func() {
		unlock()
		if drain != nil {
			drain()
		}
	}()

	if err := c.backing.DepAdd(issueID, dependsOnID, depType); err != nil {
		return err
	}

	fresh, deps, refreshed := c.refreshBeadWithDepsAfterWrite(issueID, "refresh bead after dependency add")
	c.mu.Lock()
	c.noteLocalMutationLocked(issueID)
	if refreshed {
		c.absorbFreshLocked(issueID, fresh, time.Now(), absorbOpts{
			depsMode:   depsExplicit,
			deps:       deps,
			seqMode:    seqKeep,
			clearDirty: true,
		})
		c.clearReadyProjectionLocked(issueID)
		c.markFreshLocked(time.Now())
		c.updateStatsLocked()
		c.mu.Unlock()
		drain, _ = c.enqueueOrderedCompleteChange("bead.updated", fresh)
		return nil
	}
	c.retainPendingPublication(issueID, "bead.updated")
	if !c.depsComplete {
		if _, known := c.deps[issueID]; !known {
			c.markDirtyLocked(issueID)
			c.markFreshLocked(time.Now())
			c.updateStatsLocked()
			c.mu.Unlock()
			return nil
		}
	}
	cachedDeps := c.deps[issueID]
	for i, d := range cachedDeps {
		if d.DependsOnID == dependsOnID {
			cachedDeps[i].Type = depType
			c.deps[issueID] = cachedDeps
			c.clearReadyProjectionLocked(issueID)
			c.markDirtyLocked(issueID)
			c.markFreshLocked(time.Now())
			c.updateStatsLocked()
			c.mu.Unlock()
			return nil
		}
	}
	c.deps[issueID] = append(cachedDeps, Dep{IssueID: issueID, DependsOnID: dependsOnID, Type: depType})
	c.clearReadyProjectionLocked(issueID)
	c.markDirtyLocked(issueID)
	c.markFreshLocked(time.Now())
	c.updateStatsLocked()
	c.mu.Unlock()
	return nil
}

// DepRemove removes a dependency and updates the cache.
func (c *CachingStore) DepRemove(issueID, dependsOnID string) error {
	unlock := c.lockCloseState(issueID)
	var drain func()
	defer func() {
		unlock()
		if drain != nil {
			drain()
		}
	}()

	if err := c.backing.DepRemove(issueID, dependsOnID); err != nil {
		return err
	}

	fresh, deps, refreshed := c.refreshBeadWithDepsAfterWrite(issueID, "refresh bead after dependency remove")
	c.mu.Lock()
	c.noteLocalMutationLocked(issueID)
	if refreshed {
		c.absorbFreshLocked(issueID, fresh, time.Now(), absorbOpts{
			depsMode:   depsExplicit,
			deps:       deps,
			seqMode:    seqKeep,
			clearDirty: true,
		})
		c.clearReadyProjectionLocked(issueID)
		c.markFreshLocked(time.Now())
		c.updateStatsLocked()
		c.mu.Unlock()
		drain, _ = c.enqueueOrderedCompleteChange("bead.updated", fresh)
		return nil
	}
	c.retainPendingPublication(issueID, "bead.updated")
	if !c.depsComplete {
		if _, known := c.deps[issueID]; !known {
			c.markDirtyLocked(issueID)
			c.markFreshLocked(time.Now())
			c.updateStatsLocked()
			c.mu.Unlock()
			return nil
		}
	}
	cachedDeps := c.deps[issueID]
	for i, d := range cachedDeps {
		if d.DependsOnID == dependsOnID {
			c.deps[issueID] = append(cachedDeps[:i], cachedDeps[i+1:]...)
			c.clearReadyProjectionLocked(issueID)
			c.markDirtyLocked(issueID)
			break
		}
	}
	c.markDirtyLocked(issueID)
	c.markFreshLocked(time.Now())
	c.updateStatsLocked()
	c.mu.Unlock()
	return nil
}

// Delete passes through to the backing store and removes from cache.
func (c *CachingStore) Delete(id string) error {
	unlock := c.lockCloseState(id)
	var drain func()
	defer func() {
		unlock()
		if drain != nil {
			drain()
		}
	}()

	deleted, haveDeleted := c.snapshotBeadBeforeDelete(id)
	if err := c.backing.Delete(id); err != nil {
		return err
	}

	c.mu.Lock()
	seq := c.noteLocalMutationLocked(id)
	c.tombstoneLocked(id, seq)
	c.clearDependentReadyProjectionsLocked(id)
	c.markFreshLocked(time.Now())
	c.updateStatsLocked()
	c.mu.Unlock()
	if haveDeleted {
		drain, _ = c.enqueueOrderedCompleteChange("bead.deleted", deleted)
	}
	return nil
}

// DeleteBatch forwards the batched delete capability to the backing store when
// it implements BatchDeleter, then evicts exactly those ids from the cache in
// one pass: it installs a deletion fence per id, drops their outgoing deps (via
// tombstoneLocked), and scrubs stale incoming edges from surviving beads so the
// cache mirrors the backend's ON DELETE CASCADE cleanup of edge rows. Because
// the backend orphans external dependents rather than recursively deleting them
// (see BatchDeleter), beads that merely depend on a deleted bead are preserved.
// This lets the wisp GC tear down a molecule closure with a single backing call
// instead of an O(subprocess-per-edge) loop. When the backing store lacks
// BatchDeleter, DeleteBatch falls back to a per-bead delete that first strips
// the dependency rows touching each id, so surviving dependents are orphaned
// rather than left with a dangling edge — the same contract a BatchDeleter
// backing gets from the schema's ON DELETE CASCADE. It satisfies BatchDeleter.
func (c *CachingStore) DeleteBatch(ids []string) error {
	cd, ok := c.backing.(BatchDeleter)
	if !ok {
		for _, id := range ids {
			if id == "" {
				continue
			}
			if err := c.deleteOrphaningDeps(id); err != nil {
				return err
			}
		}
		return nil
	}
	if len(ids) == 0 {
		return nil
	}
	unlock := c.lockCloseState(ids...)
	var drains []func()
	defer func() {
		unlock()
		for _, drain := range drains {
			drain()
		}
	}()

	// Snapshot bead.deleted payloads from the cache only. Unlike Delete, which
	// reads each snapshot from the backing store, forwarding N backing Get calls
	// here would reintroduce the per-bead subprocess storm this batch path exists
	// to remove; a bead absent from the cache is still evicted but emits no
	// event. In practice the wisp GC lists the closure just before deleting it,
	// so members are warm in the cache.
	deleted := make(map[string]struct{}, len(ids))
	c.mu.RLock()
	events := make([]Bead, 0, len(ids))
	for _, id := range ids {
		if id == "" {
			continue
		}
		deleted[id] = struct{}{}
		if b, ok := c.beads[id]; ok {
			events = append(events, cloneBead(b))
		}
	}
	c.mu.RUnlock()
	pendingDeleteSnapshots := c.pendingSnapshotsForDelete(ids)

	if err := cd.DeleteBatch(ids); err != nil {
		drains = c.enqueueOrderedChanges(c.reconcilePartialBatchDelete(err, ids, events, pendingDeleteSnapshots))
		return err
	}

	c.mu.Lock()
	c.evictBatchDeletedLocked(deleted)
	c.mu.Unlock()

	notifications := c.batchDeleteNotifications(ids, nil, events, pendingDeleteSnapshots)
	drains = c.enqueueOrderedChanges(notifications)
	return nil
}

// evictBatchDeletedLocked removes exactly the ids in deleted from the cache:
// per-id local-mutation fence + tombstone and dropped dependent ready
// projections, then a single scrub of inbound edges from survivors — mirroring
// the backend's ON DELETE CASCADE cleanup of the deleted beads' edge rows.
// Callers must hold c.mu.
func (c *CachingStore) evictBatchDeletedLocked(deleted map[string]struct{}) {
	for id := range deleted {
		seq := c.noteLocalMutationLocked(id)
		c.tombstoneLocked(id, seq)
		c.clearDependentReadyProjectionsLocked(id)
	}
	c.dropIncomingEdgesToDeletedLocked(deleted)
	c.markFreshLocked(time.Now())
	c.updateStatsLocked()
}

// reconcilePartialBatchDelete handles a backing DeleteBatch error. A
// chunk-committing backend (BdStore) can durably remove earlier chunks before a
// later chunk fails, reporting the removed ids via *BatchDeleteError. This
// evicts exactly those committed ids and fires their bead.deleted events so a
// mid-batch failure never leaves a deleted bead present-but-stale in the cache,
// while the uncommitted ids stay resident because the backing did not remove
// them. The original error is always returned so the caller still sees the
// failure; a backing that reports no committed ids leaves the cache untouched.
func (c *CachingStore) reconcilePartialBatchDelete(
	err error,
	ids []string,
	events []Bead,
	pendingDeleteSnapshots map[string]cachePendingRecovery,
) []cacheNotification {
	var batchErr *BatchDeleteError
	if !errors.As(err, &batchErr) || len(batchErr.Committed) == 0 {
		return nil
	}
	committed := make(map[string]struct{}, len(batchErr.Committed))
	for _, id := range batchErr.Committed {
		if id != "" {
			committed[id] = struct{}{}
		}
	}
	if len(committed) == 0 {
		return nil
	}
	c.mu.Lock()
	c.evictBatchDeletedLocked(committed)
	c.mu.Unlock()
	return c.batchDeleteNotifications(ids, committed, events, pendingDeleteSnapshots)
}

func (c *CachingStore) pendingSnapshotsForDelete(ids []string) map[string]cachePendingRecovery {
	all := c.pendingPublications.snapshot()
	if len(all) == 0 {
		return nil
	}
	selected := make(map[string]cachePendingPublication)
	for _, id := range ids {
		if publication, ok := all[id]; ok {
			selected[id] = publication
		}
	}
	recovered, _, _ := c.readPendingPublications(selected)
	return recovered
}

func (c *CachingStore) batchDeleteNotifications(
	ids []string,
	committed map[string]struct{},
	events []Bead,
	pendingDeleteSnapshots map[string]cachePendingRecovery,
) []cacheNotification {
	eventByID := make(map[string]Bead, len(events))
	for _, bead := range events {
		eventByID[bead.ID] = bead
	}
	notifications := make([]cacheNotification, 0, len(eventByID)+len(pendingDeleteSnapshots))
	seen := make(map[string]struct{}, len(ids))
	for _, id := range ids {
		if id == "" {
			continue
		}
		if _, duplicate := seen[id]; duplicate {
			continue
		}
		seen[id] = struct{}{}
		if committed != nil {
			if _, ok := committed[id]; !ok {
				continue
			}
		}
		if recovery, ok := pendingDeleteSnapshots[id]; ok {
			notifications = append(notifications, cacheNotification{
				eventType:      "bead.deleted",
				bead:           cloneBead(recovery.bead),
				resolvePending: true,
			})
			continue
		}
		if bead, ok := eventByID[id]; ok {
			notifications = append(notifications, cacheNotification{eventType: "bead.deleted", bead: bead})
		}
	}
	return notifications
}

// deleteOrphaningDeps removes id after stripping every dependency row touching
// it in both directions, so surviving beads that depend on id are orphaned
// rather than left with a dangling edge. DeleteBatch uses it as the fallback
// when the backing store does not implement BatchDeleter: a bare backing Delete
// (MemStore, FileStore, and other non-BatchDeleter stores) drops only the bead
// row, so DeleteBatch must clean the edge rows itself to honor the same
// orphaning contract a BatchDeleter backing gets from the schema's ON DELETE
// CASCADE. It performs the same edge-strip-then-delete as the per-bead workflow
// delete (deleteWorkflowBead in cmd/gc), and the DepRemove/Delete methods it
// calls keep the cache coherent. Unlike deleteWorkflowBead it intentionally does
// not roll back already-stripped edges when a mid-strip DepRemove or the final
// Delete fails: this fallback runs only against non-BatchDeleter backings
// (MemStore/FileStore), whose in-memory edge operations do not fail partway, and
// the wisp GC re-collects and re-deletes any half-stripped member idempotently
// on a later tick.
func (c *CachingStore) deleteOrphaningDeps(id string) error {
	downDeps, err := c.DepList(id, "down")
	if err != nil {
		return fmt.Errorf("list down deps for %s: %w", id, err)
	}
	for _, dep := range downDeps {
		if err := c.DepRemove(id, dep.DependsOnID); err != nil {
			return fmt.Errorf("remove down dep %s -> %s: %w", id, dep.DependsOnID, err)
		}
	}
	upDeps, err := c.DepList(id, "up")
	if err != nil {
		return fmt.Errorf("list up deps for %s: %w", id, err)
	}
	for _, dep := range upDeps {
		if err := c.DepRemove(dep.IssueID, id); err != nil {
			return fmt.Errorf("remove up dep %s -> %s: %w", dep.IssueID, id, err)
		}
	}
	return c.Delete(id)
}

// dropIncomingEdgesToDeletedLocked scrubs cached dependency rows that point at a
// just-deleted bead, mirroring the backend's ON DELETE CASCADE cleanup of the
// deleted beads' edge rows. Surviving beads are kept; only their now-dangling
// edges into the deleted set are removed. Callers must hold c.mu.
func (c *CachingStore) dropIncomingEdgesToDeletedLocked(deleted map[string]struct{}) {
	for issueID, deps := range c.deps {
		if _, gone := deleted[issueID]; gone {
			continue
		}
		kept := deps[:0]
		changed := false
		for _, d := range deps {
			if _, gone := deleted[d.DependsOnID]; gone {
				changed = true
				continue
			}
			kept = append(kept, d)
		}
		if !changed {
			continue
		}
		if len(kept) == 0 {
			delete(c.deps, issueID)
		} else {
			c.deps[issueID] = kept
		}
		c.clearReadyProjectionLocked(issueID)
	}
}

func (c *CachingStore) snapshotBeadBeforeDelete(id string) (Bead, bool) {
	deleted, _, err := c.readBeadWithDeps(id)
	if err != nil {
		if errors.Is(err, ErrNotFound) {
			return Bead{}, false
		}
		c.recordProblem("snapshot bead before delete", fmt.Errorf("%s: %w", id, err))
		return Bead{}, false
	}
	return deleted, true
}

func applyUpdateOptsToBead(bead Bead, opts UpdateOpts) Bead {
	if opts.Title != nil {
		bead.Title = *opts.Title
	}
	if opts.Status != nil {
		bead.Status = *opts.Status
	}
	if opts.Type != nil {
		bead.Type = *opts.Type
	}
	if opts.Priority != nil {
		bead.Priority = cloneIntPtr(opts.Priority)
	}
	if opts.Description != nil {
		bead.Description = *opts.Description
	}
	if opts.ParentID != nil {
		bead.ParentID = *opts.ParentID
	}
	if opts.Assignee != nil {
		bead.Assignee = *opts.Assignee
	}
	if len(opts.Metadata) > 0 {
		if bead.Metadata == nil {
			bead.Metadata = make(map[string]string, len(opts.Metadata))
		}
		for key, value := range opts.Metadata {
			bead.Metadata[key] = value
		}
	}
	if len(opts.Labels) > 0 || len(opts.RemoveLabels) > 0 {
		remove := make(map[string]struct{}, len(opts.RemoveLabels))
		for _, label := range opts.RemoveLabels {
			remove[label] = struct{}{}
		}

		labels := make([]string, 0, len(bead.Labels)+len(opts.Labels))
		seen := make(map[string]struct{}, len(bead.Labels)+len(opts.Labels))
		for _, label := range bead.Labels {
			if _, drop := remove[label]; drop {
				continue
			}
			if _, exists := seen[label]; exists {
				continue
			}
			labels = append(labels, label)
			seen[label] = struct{}{}
		}
		for _, label := range opts.Labels {
			if _, drop := remove[label]; drop {
				continue
			}
			if _, exists := seen[label]; exists {
				continue
			}
			labels = append(labels, label)
			seen[label] = struct{}{}
		}
		bead.Labels = labels
	}
	return bead
}
